version: "3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    networks:
      - atacado-net
    restart: unless-stopped
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - db-volume:/data/db
    networks:
      - atacado-net
    restart: unless-stopped
volumes:
  db-volume:
networks:
  atacado-net: